### ISSUE TITLE
ER Diagramm

### ISSUE THREAD

**Issue by tristan2407** [tristan2407/databases#1]
![ER Diagramm](https://user-images.githubusercontent.com/62421573/77160440-9b8ccc80-6aa7-11ea-99b9-5cabe200634b.png)

**Comment by tristan2407** [comment]
Hey Leute, das ist jetzt mal das "grobe" ER Diagramm.. die keys müssten eigentlich stimmen oder?

**Comment by MarcelGardias** [comment]
Die Linien fehlen und die Beziehungen in welchen die Objekte mit einander stehen, aber sonst ist das richtig.

**Comment by tristan2407** [comment]
ich sagte ja --> grob^^
